<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products [
        <!ELEMENT products (items)*>
        <!ELEMENT items (item)+>
        <!ATTLIST items
                type ID #REQUIRED>
        <!ELEMENT item (name,price,prod_year,prod_country,image,params+)>
        <!ATTLIST item
                s_num ID #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT prod_year (#PCDATA)>
        <!ELEMENT prod_country (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT params (param+)>
        <!ELEMENT param (param_name,param_value)>
        <!ELEMENT param_name (#PCDATA)>
        <!ELEMENT param_value (#PCDATA)>
        ]>
<products>
    <items type="Computers">
        <item s_num="DT87EA">
            <name>HP Pavilion Gaming</name>
            <price>3456 $</price>
            <prod_year>2016</prod_year>
            <prod_country>Canada</prod_country>
            <image>Computer1.png</image>
            <params>
                <param>
                    <param_name>Brand</param_name>
                    <param_value><![CDATA[ZFT&X_F]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[8]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="Y89T87EA">
            <name>Mac 56</name>
            <price>2343 $</price>
            <prod_year>2013</prod_year>
            <prod_country>USA</prod_country>
            <image>Computer3.png</image>
            <params>
                <param>
                    <param_name>Rom</param_name>
                    <param_value><![CDATA[16]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[8]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="G689GYH6">
            <name>HP X 86</name>
            <price>3778.89 $</price>
            <prod_year>2015</prod_year>
            <prod_country>USA</prod_country>
            <image>Computer2.png</image>
            <params>
                <param>
                    <param_name>Rom</param_name>
                    <param_value><![CDATA[16]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[8]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="T45GTYH67">
            <name>Lenovo X67</name>
            <price>3555 $</price>
            <prod_year>2016</prod_year>
            <prod_country>Australia</prod_country>
            <image>Computer4.jpg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[red]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[8]]></param_value>
                </param>
            </params>
        </item>
    </items>
    <items type="Phones">
        <item s_num="DT7EAE">
            <name>IPhone X</name>
            <price>999.78 $</price>
            <prod_year>1995</prod_year>
            <prod_country>USA</prod_country>
            <image>i12.jpg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[green]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[32]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="FTG78GT">
            <name>IPhone 10</name>
            <price>780 $</price>
            <prod_year>2011</prod_year>
            <prod_country>USA</prod_country>
            <image>iphpro.jpg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[black]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="AE1010AE">
            <name>IPhone 7</name>
            <price>566 $</price>
            <prod_year>2011</prod_year>
            <prod_country>UK</prod_country>
            <image>iph11max.jpg</image>
            <params>
                <param>
                    <param_name>Brand</param_name>
                    <param_value><![CDATA[QWERTY]]></param_value>
                </param>
                <param>
                    <param_name>Ram</param_name>
                    <param_value><![CDATA[8]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="AE56TF7Y">
            <name>IPhone 11 Pro Max</name>
            <price>666 $</price>
            <prod_year>2020</prod_year>
            <prod_country>USA</prod_country>
            <image>iphone-11-pro-max.jpeg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[gold]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="R7OPKJ90">
            <name>Xiaomi Redmi Note 8</name>
            <price>994 $</price>
            <prod_year>2018</prod_year>
            <prod_country>UA</prod_country>
            <image>xi.jpg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[blue]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="YHJU67Y">
            <name>Nokia X Pro</name>
            <price>999.9 $</price>
            <prod_year>2019</prod_year>
            <prod_country>USA</prod_country>
            <image>nokia.jpg</image>
            <params>
                <param>
                    <param_name>Color</param_name>
                    <param_value><![CDATA[black & red]]></param_value>
                </param>
            </params>
        </item>
    </items>
    <items type="Mouses">
        <item s_num="ae">
            <name>Mouse Pro Gamer</name>
            <price>45.9 $</price>
            <prod_year>2019</prod_year>
            <prod_country>USA</prod_country>
            <image>ms.jpg</image>
            <params>
                <param>
                    <param_name>Number of buttons</param_name>
                    <param_value><![CDATA[3]]></param_value>
                </param>
            </params>
        </item>
        <item s_num="Ratatouille">
            <name>Remy</name>
            <price>12.99 $</price>
            <prod_year>2000</prod_year>
            <prod_country>France</prod_country>
            <image>remy.png</image>
            <params>
                <param>
                    <param_name>Number of eyes</param_name>
                    <param_value><![CDATA[2]]></param_value>
                </param>
                <param>
                    <param_name>Number of paws</param_name>
                    <param_value><![CDATA[4]]></param_value>
                </param>
                <param>
                    <param_name>Number of ears</param_name>
                    <param_value><![CDATA[2]]></param_value>
                </param>
            </params>
        </item>
    </items>
</products>